### ISSUE TITLE
[Bug] There is an indexing problem in mobile UI

### ISSUE THREAD

**Issue by HemantBatra873** [himeshparashar/Social-Morph#101]
**Problem**
In the mobile UI when I opened the dropdown list for the features and pricing . The search bar came on top of it and due to this whatever was written on the back was not visible . The search bar must be backside on the z-index . 

---

![Social morph issuse](https://github.com/user-attachments/assets/621ed73b-abbe-40d1-a7a9-9579884b0e57)

---

Please assign me this issue with hacktoberfest-accepted and gsscoc-ext labels . @himeshparashar

**Comment by himeshparashar** [comment]
@HemantBatra873  you can work on this

**Comment by HemantBatra873** [comment]
> @HemantBatra873 you can work on this

@himeshparashar I have fixed and opened the pull request .
