### ISSUE TITLE
Add Transitions to stats

### ISSUE THREAD

**Issue by haseebzaki-07** [himeshparashar/Social-Morph#110]
I want to add transition to stats that looks like counter starting from 0 to the current numeric values. Making it more aesthetic and visually appealing.

![Screenshot 2024-10-17 130046](https://github.com/user-attachments/assets/b82ff78e-5f70-40f1-89b0-448e52fca741)

**Comment by himeshparashar** [comment]
@haseebzaki-07 you can work on the issue
