### ISSUE TITLE
[Feat] : Convert current Dockerfile to a Multi-Staged one

### ISSUE THREAD

**Issue by vivekrawat21** [himeshparashar/Social-Morph#114]
Description: The current Dockerfile is not configured as a multi-stage build, which may lead to larger image sizes and increased complexity when separating build dependencies from the runtime environment. By implementing a multi-stage build, we can optimize the image size, improve build performance, and ensure a cleaner and more efficient production image.

Tasks:
Convert the existing Dockerfile to use multi-stage builds.
Split the build and runtime stages for optimal layering.
Ensure that only production dependencies are included in the final image.
Test the new multi-stage Dockerfile to ensure it builds and runs correctly.
Benefits of Multi-Stage Builds:

Reduced Image Size: By excluding unnecessary build dependencies and files, the final image will be smaller, which leads to faster pulls and more efficient storage.
Better Security: Since only the minimal set of dependencies and files necessary for running the application are included, this reduces the attack surface.
Cleaner Separation of Stages: Development tools and dependencies will not leak into the production image, leading to a cleaner runtime environment.
Build Efficiency: Reusable layers and minimized context reduce build times, especially when using Docker's layer caching.

**Comment by XIVASSS** [comment]
https://github.com/himeshparashar/Social-Morph/pull/147

Hi, I've completed the work on this issue by optimizing the Dockerfile with a multi-stage build approach. This change reduces the final image size and ensures that only production dependencies are included in the runtime environment.

I’ve tested the changes locally, and everything is functioning as expected. I’ll be submitting a pull request shortly for review.

Please let me know if there are any additional details or requirements I should consider. Thanks!
