### ISSUE TITLE
"Get Started" Button Non-Functional; Need Login, Registration, and Forgot Password Pages

### ISSUE THREAD

**Issue by myselfshivams** [himeshparashar/Social-Morph#12]
Currently, when the "Get Started" button is clicked, nothing happens, leading to confusion for users. To improve user experience and functionality, we need to implement the following:

- A Login Page for existing users.
- A Registration Page for new users to create an account.
- A Forgot Password Page for users who need to reset their passwords.

@himeshparashar Please assign this issue to me (@myselfshivams).

Labels:
- GSSoC
- Hacktoberfest

**Comment by aarch34** [comment]
Hi, i can create a login page for existing users and and registration page for new users, please assign this part to me

**Comment by himeshparashar** [comment]
@myselfshivams  go ahead I want a layout something like this

the signup page is like a multistep loader and also act as a user onbaording process

![image](https://github.com/user-attachments/assets/59d2cafc-145e-4a0d-97a4-149ef10180a2)


![image](https://github.com/user-attachments/assets/b237b35a-7664-4b50-be40-5f6d3c986afa)


![image](https://github.com/user-attachments/assets/a4447c7f-03cd-4378-91de-654d4649189c)

**Comment by himeshparashar** [comment]
@myselfshivams please first work on other issues assigned to you

**Comment by aarch34** [comment]
hi @himeshparashar can you give me more details on what youre looking for? can i use clerk for registration?

**Comment by himeshparashar** [comment]
@aarch34 in the auth part i will use clerk but not the default clerk auth UI 

### Don't want this as a Login component , but something in the above refrences
![image](https://github.com/user-attachments/assets/ffae3d91-30cd-46b9-8a26-2c8255a4d9f2)

for reference of custom clerk form https://mango-grammerjam.hashnode.dev/how-to-create-custom-clerk-auth-forms-with-next-typescript-and-tailwind

**Comment by aarch34** [comment]
okay ill just be making the frontend then?

**Comment by himeshparashar** [comment]
@aarch34 any updates ?

**Comment by aarch34** [comment]
my code is clashing with the code other people wrote, please unassign me this issue
