### ISSUE TITLE
Add AI-Powered Hashtag Suggestions for Social Media Posts

### ISSUE THREAD

**Issue by sezallagwal** [himeshparashar/Social-Morph#124]
Enhance Social Morph's capabilities by integrating an AI-powered hashtag suggestion feature. This feature should analyze the content of the user's post or the provided keywords and suggest trending and relevant hashtags that can maximize the reach and engagement of the post.

Requirements:

Implement an AI-based algorithm to analyze the content of the post.
Provide a list of relevant hashtags based on current trends and keywords.

@himeshparashar please assign this to me under gssoc-ext and hacktoberfest

**Comment by himeshparashar** [comment]
@sezallagwal if implemented completely with the ui then it's a level 3 , you can go ahead with the dev
