### ISSUE TITLE
Home page search bar work on pressing enter

### ISSUE THREAD

**Issue by anishka25** [himeshparashar/Social-Morph#126]
Currently the home page search bar after entering the website url doesnt go forward to the sign in page. The pr following this issue will allow the user to do so.

**Comment by himeshparashar** [comment]
@anishka25 currently auth needs to be integrated, the backend is ready but needs to be integrated

**Comment by anishka25** [comment]
@himeshparashar Hey, we don't need auth, its a frontend only thing which needs to implemented to improve the user experience.

**Comment by himeshparashar** [comment]
@anishka25 I checked the get posts now points to /dashboard which is a protected route so it redirects to auth page

**Comment by anishka25** [comment]
@himeshparashar Hey my issue was that it only moves forward to /dashboard when the button is clicked not when enter key is pressed but it should as it improves user experience.

**Comment by himeshparashar** [comment]
@anishka25 ok you can start with this and also add URL validation in the input along with this issue
