### ISSUE TITLE
Create a Pricing Page with Information Cards

### ISSUE THREAD

**Issue by myselfshivams** [himeshparashar/Social-Morph#13]
Currently, there is no pricing page available on the website. To provide users with clear information about our services, we need to create a dedicated pricing page. This page should feature information cards that display sample pricing information for different services or plans.

@himeshparashar Please assign this issue to me(@myselfshivams).

Labels:
- GSSoC
- Hacktoberfest

**Comment by himeshparashar** [comment]
@myselfshivams Go ahead with the pricing section and keep it mind to match the website theme

**Comment by tarunkumar2005** [comment]
@himeshparashar Its been a week issue is not solved so you can assign this to me for faster solution. i can work on this.

**Comment by himeshparashar** [comment]
@Shobhit-Nagpal please check this , and if you feel then assign it to @tarunkumar2005  so that he can start working on this

**Comment by AdityaBavadekar** [comment]
@himeshparashar Can I work on this? I will surely complete the task in 2 days.

**Comment by himeshparashar** [comment]
@tarunkumar2005 if you want to start working on this please ping me so that I may take you in consideration for this

**Comment by tarunkumar2005** [comment]
@himeshparashar I will work on this

**Comment by AdityaBavadekar** [comment]
@himeshparashar I can contribute to this.

**Comment by tarunkumar2005** [comment]
@himeshparashar Close this issue as it is completed.
