### ISSUE TITLE
[UI] Updating company name in copywrite

### ISSUE THREAD

**Issue by tanishirai** [himeshparashar/Social-Morph#148]
**Description**
Copywrite must be owned by Social Morph

**Current Behavior**
Currently it displays 'Your Company'

**Proposed Behavior**
I would like to update that

**Screenshots**
Currenlty
![image](https://github.com/user-attachments/assets/626ba23f-9e17-4ecd-9c9c-adc19f844a00)

I would improve to 
![image](https://github.com/user-attachments/assets/ace26cb2-40dc-4108-bbe8-27b106bae4bf)

**Additional Context**

**Impact**
legal protection

**Related Issues**

**Comment by himeshparashar** [comment]
@tanishirai currently i don't own any copyright for this website and also this is a very minor change so won't be count for hacktoberfest if you are targeting that
