### ISSUE TITLE
Docker and Docker File Addition

### ISSUE THREAD

**Issue by adityapandey23** [himeshparashar/Social-Morph#15]
I see that in the README it's mentioned that the project can run locally using docker but there isn't support for it yet. I would love to add the docker file as well as the docker compose file for the project. Can you assign this to me ?

**Comment by himeshparashar** [comment]
go ahead with dockerfile and also you can create a dockercompose file also and then add setup instructions in documentation

**Comment by adityapandey23** [comment]
okay on it!

**Comment by adityapandey23** [comment]
Hey @himeshparashar @Shobhit-Nagpal 
I have added the Dockerfile, .dockerignore and the docker-compose.yml file to the repo 
Here is the demo:

**Comment by adityapandey23** [comment]
Hey @himeshparashar @Shobhit-Nagpal 
I have added the Dockerfile, .dockerignore and the docker-compose.yml file to the repo
Here is the demo:

https://github.com/user-attachments/assets/50f317ab-1840-4239-a065-1bd05cb582c1

(hehe did the rookie mistake...something was already running on 3000 on my host machine)

https://github.com/user-attachments/assets/d43f96b8-6c56-44e6-a49a-598f90ee935e

Give me a green flag and I'll create a pull request

(Also please assign levels too to the issues otherwise no points for GsSoc🥺)

**Comment by Shobhit-Nagpal** [comment]
@himeshparashar we'll need to add level labels on the repo too, otherwise the PRs won't count

**Comment by adityapandey23** [comment]
Should I create a PR or wait for a green signal?

**Comment by Shobhit-Nagpal** [comment]
@adityapandey23 i'd suggest wait for us to add the labels on the repo. once they're added, you can open up a pr for this

**Comment by himeshparashar** [comment]
@adityapandey23  you can now raise a pr for this

**Comment by adityapandey23** [comment]
@himeshparashar Done!
