### ISSUE TITLE
UI fix: change this misalignments

### ISSUE THREAD

**Issue by AE-Hertz** [himeshparashar/Social-Morph#150]
fix the alignments with irregular gaps and margins with adding responsiveness.

![Screenshot 2024-10-22 110621](https://github.com/user-attachments/assets/8796d0f8-af34-4bb3-8bc1-c36892e4a063)

assign me this task under hacktoberfest and gssoc-ext

**Comment by AE-Hertz** [comment]
@himeshparashar can you assign me this and other issues raised my me, asap , as gssoc-ext is about to over, thanks

**Comment by himeshparashar** [comment]
@AE-Hertz, could you please specify where the alignment issue is? It looks fine to me.

**Comment by AE-Hertz** [comment]
@himeshparashar hello i have tried to demonstrate through paint, pls ignore my bad drawing skills.


![Screenshot 2024-10-29 201312](https://github.com/user-attachments/assets/c44feb23-ccad-4f56-a6db-f7ac67db4823)

**Comment by AE-Hertz** [comment]
the social should be aligned with social morph line and the email too, the linkedin content creation made easy should be center under the social morph logo Heading.

Hope i am able to convey idea through my words.

**Comment by himeshparashar** [comment]
@AE-Hertz you can work on this issue

also change the Linkedin content cre...
to Social Media content crea....

**Comment by AE-Hertz** [comment]
@himeshparashar i am done making it, requested for PR,
and please assign me the new issues too.
 thank you.
