### ISSUE TITLE
UI fix: fix the body styling 

### ISSUE THREAD

**Issue by AE-Hertz** [himeshparashar/Social-Morph#151]
fix the body and their alignments.

![Screenshot 2024-10-22 110915](https://github.com/user-attachments/assets/3fbe71c2-3591-4930-8bd8-eafb04994587)

assign me this task under hacktoberfest and gssoc-ext

**Comment by himeshparashar** [comment]
start with this issue @AE-Hertz

**Comment by AE-Hertz** [comment]
![Screenshot 2024-10-24 130930](https://github.com/user-attachments/assets/c1f53ced-3c23-4483-8134-4234d2bc52d1)
@himeshparashar hey can you confirm this asap. is this UI changes looks good? or i should keep the old design and work on that?

**Comment by AE-Hertz** [comment]
anyway i implemented this design and fixed the issue, sending PR ,
![Screenshot 2024-10-24 131907](https://github.com/user-attachments/assets/fdddf69e-9a9b-42b9-87c2-27db0e440472)
if their is any changes required let me know.
