### ISSUE TITLE
[FEATURE] Adding Scroll Progress Bar 

### ISSUE THREAD

**Issue by RachitSahu26** [himeshparashar/Social-Morph#154]
**Is your feature request related to a problem? Please describe.**
I would like to implement a scroll progress bar that visually indicates the current scroll position on the page. This could be a horizontal bar at the top of the viewport that fills up as the user scrolls down, providing a clear visual cue of how much content has been viewed.
**Describe the solution you'd like**
I considered adding a percentage indicator next to the scroll bar, but I think a visual progress bar would be more intuitive and visually appealing. Another alternative could be a floating button that allows users to scroll back to the top, but this doesn't provide the same contextual feedback about their current position.
**Describe alternatives you've considered**

**Additional context**

**Comment by RachitSahu26** [comment]
i would like to work on it please assign me @himeshparashar

**Comment by himeshparashar** [comment]
@RachitSahu26 issue already exists https://github.com/himeshparashar/Social-Morph/issues/142
