### ISSUE TITLE
[FEATURE] Implementation of Newsletter/Trial Form | Toast Notification Implementation

### ISSUE THREAD

**Issue by Shariq2003** [himeshparashar/Social-Morph#156]
**Is your feature request related to a problem? Please describe.**
Yes, currently the trial or newsletter or subscription form is not functional.

**Describe the solution you'd like**
I want to implement the newsletter form logic along with the Toast Notification

![image](https://github.com/user-attachments/assets/06aeea6b-5eae-4f3d-ba21-5e8e0e9d4656)

**Comment by Shariq2003** [comment]
@himeshparashar sir please assign this to me.

**Comment by himeshparashar** [comment]
@Shariq2003 no need of a newsletter or trial form , as looking forward with a user login and business setup flow for the trial
