### ISSUE TITLE
Implement Blog page || As of now it takes us to no where 

### ISSUE THREAD

**Issue by shubhagarwal1** [himeshparashar/Social-Morph#163]
- Implement an elligant blgo page
- This page will have cards which will show blogs 
- have a search bar 
- style matching to the website

**Comment by shubhagarwal1** [comment]
Hey @himeshparashar can you tell me anything else which i can work on, it would be great opoortunity for me.

**Comment by himeshparashar** [comment]
@shubhagarwal1 connect with me on linkedin
