### ISSUE TITLE
[FEATURE]:click navbar logo to homepage

### ISSUE THREAD

**Issue by JayrajSingh65** [himeshparashar/Social-Morph#166]
**Is your feature request related to a problem? Please describe.**  
I'm always frustrated when I click on the navbar logo, but it doesn't redirect me to the homepage. This is a common navigation behavior, and it creates confusion when the logo doesn't function as expected.

**Describe the solution you'd like**  
I would like the logo in the navbar to act as a link to the homepage, ensuring users can easily return to the main page from any section of the site with a single click.

**Describe alternatives you've considered**  
- Adding a dedicated "Home" button to the navbar.
- Including a separate "Back to homepage" link in the footer, but this isn’t as intuitive or commonly expected as the logo linking back to the homepage.

**Additional context**  
Many websites use the logo as a homepage link, so users have come to expect this behavior. Making this change would improve the site's usability and align with common web navigation standards.

**Comment by PriyanshuValiya** [comment]
@JayrajSingh65 Assign me this issue.

**Comment by RachitSahu26** [comment]
please assign me this issue @himeshparashar
