### ISSUE TITLE
[FEATURE]: Error 404 page design 

### ISSUE THREAD

**Issue by dev129** [himeshparashar/Social-Morph#167]
Hi @himeshparashar 
**Is your feature request related to a problem? Please describe.**  
I often encounter users landing on broken links or non-existent pages, which leads to confusion and frustration. An error 404 page can help guide users back to functional areas of the site.

**Describe the solution you'd like**  
I would like a custom 404 error page for Social Morph that includes a friendly message explaining the error, a search bar to help users find what they're looking for, and links to popular sections of the website. Additionally, it should have a visual design that aligns with the branding of Social Morph.

**Describe alternatives you've considered**  
Currently, there is a generic 404 error page that lacks any guidance or branding. An alternative could be using a simple redirect to the homepage, but this doesn't inform users about the broken link and can lead to further confusion.

**Additional context**  
A well-designed 404 page not only improves user experience but also reflects positively on the brand. Including elements like humor or engaging visuals could enhance user retention even when they encounter an error.

**Comment by PriyanshuValiya** [comment]
@dev129  Assign me this issue.

**Comment by himeshparashar** [comment]
issue already conidered https://github.com/himeshparashar/Social-Morph/issues/74
