### ISSUE TITLE
Add code_of_conduct.md

### ISSUE THREAD

**Issue by kartikey369-ind** [himeshparashar/Social-Morph#17]
How about adding a code_of_conduct.md file to this repository

**Comment by himeshparashar** [comment]
@kartikey369-ind  please go ahead as this is needed and  also give setup steps inside the documentation also please create a contributors.md file also

**Comment by himeshparashar** [comment]
also add .env example also for setup 
```
NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=
CLERK_SECRET_KEY=

NEXT_PUBLIC_CLERK_SIGN_IN_URL=/sign-in
NEXT_PUBLIC_CLERK_SIGN_UP_URL=/sign-up

NEXT_PUBLIC_GOOGLE_GEMINI_API_KEY=
```

**Comment by kartikey369-ind** [comment]
can you add hacktoberfest lable if possible

**Comment by MitulSonagara** [comment]
@himeshparashar 

As this issue is not solved since 5 days.
can you assign it to me I can work on this with in a day

**Comment by himeshparashar** [comment]
@MitulSonagara  You can go ahead with the issue, if you create the PR first then it's you'r
