### ISSUE TITLE
[BUG]  Footer Links Not Redirecting to Respective Pages

### ISSUE THREAD

**Issue by sezallagwal** [himeshparashar/Social-Morph#172]
### Description

The footer contains links to various sections like "Features," "Pricing," "Blog," and "FAQ," but these links are not properly connected to their respective pages. When clicked, they do not redirect users to the intended sections.

### Screenshots

![image](https://github.com/user-attachments/assets/13c0c238-823d-4ed6-8c74-8d101d4be14f)

## Acceptance Criteria
- [x] Footer links are functional and redirect users to their respective pages.
- [x] Links are tested for both desktop and mobile devices.
- [x] No broken links or errors when clicked.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/YadavAkhileshh/Alien-Invasion-Defense/blob/main/Code_Of_Conduct.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by himeshparashar** [comment]
@sezallagwal you can start working on this
