### ISSUE TITLE
[FEATURE] Adding feedback form

### ISSUE THREAD

**Issue by TBorundia** [himeshparashar/Social-Morph#173]
Create a feedback form to collect user input and improve website features. The form should include the following:

Input fields for name, email, and feedback message.
A star rating system for user satisfaction.
Form validation to ensure all fields are correctly filled before submission.
A responsive design that works seamlessly on all devices.
A success/failure message after form submission.

**Comment by himeshparashar** [comment]
![image](https://github.com/user-attachments/assets/d29b43da-7512-48f7-b67a-9ba8784e6208)
issue  looks similar to this
