### ISSUE TITLE
improve the sign up and login page UI

### ISSUE THREAD

**Issue by muskan-fatim** [himeshparashar/Social-Morph#185]
UI of login page and sign up and login page is good but it's postion create mess and i think there is alo need of nav bar or backt to home button

![image](https://github.com/user-attachments/assets/d6e4b2a0-3f96-43d0-aec0-12e5d3a121c3)

**Comment by sudhanshutech** [comment]
@muskan-fatim please add proper title instead just [UI] to the issue

**Comment by muskan-fatim** [comment]
@sudhanshutech thanks

**Comment by himeshparashar** [comment]
@muskan-fatim 
https://github.com/himeshparashar/Social-Morph/pull/102
A new UI already there , but needs to integrate
