### ISSUE TITLE
[BUG] GEMINI API KEY MISSING

### ISSUE THREAD

**Issue by vastavikadi** [himeshparashar/Social-Morph#186]
### Description

GEMINI API KEY is missing, that will not let users log in and throws out errors.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/YadavAkhileshh/Alien-Invasion-Defense/blob/main/Code_Of_Conduct.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by himeshparashar** [comment]
the env variable name was incorrect
