### ISSUE TITLE
[FEATURE]: Frequently asked questions accordion is too small in the mobile version

### ISSUE THREAD

**Issue by Hemraj-7** [himeshparashar/Social-Morph#187]
**Is your feature request related to a problem? Please describe.**
Frequently asked questions accordion is too small in the mobile version.

![Screenshot 2024-11-09 183622](https://github.com/user-attachments/assets/b9cfe65b-c889-4254-a34b-8c6d98c6788f)

**Describe the solution you'd like**
In the mobile version. it's width is too small. now it's width is 66% this is not enough. it should have 80% of width for getting better user Experience.

I want to work on this issue
Assign me this issue
Thank you!

**Comment by himeshparashar** [comment]
@Hemraj-7 you can work on this issue

**Comment by Hemraj-7** [comment]
> @Hemraj-7 you can work on this issue

Yes
