### ISSUE TITLE
Create a Dashboard page, after user onboarding and "Get Started"

### ISSUE THREAD

**Issue by himeshparashar** [himeshparashar/Social-Morph#22]
#### Description
We currently have a landing page in place, and we would like to enhance the user experience by implementing a dashboard UI that appears after the user clicks the Call to Action (CTA) button. The dashboard should provide an intuitive interface for users to interact with our features and data.

#### Requirements
- **Dashboard Layout**: Create a responsive layout that aligns with the rough sketch attached in this comment.
- **Components**: Implement necessary components such as charts, tables, and navigation elements as outlined in the sketch.
- **Styling**: Maintain consistent styling with the existing landing page and ensure the UI is visually appealing.

#### Attached Sketch
Please find the rough sketch attached to this comment for reference. Use it as a guideline for the layout and functionality of the dashboard.

#### Additional Notes
- Consider accessibility and responsiveness for different screen sizes.
- If possible, incorporate any existing design tokens or styles from the landing page to maintain a cohesive look and feel.

#### Acceptance Criteria
- [ ] Dashboard UI is implemented as per the attached sketch.
- [ ] Transition from landing page to dashboard is smooth.
- [ ] All components are functional and styled appropriately.

Looking forward to seeing the progress on this!

![image](https://github.com/user-attachments/assets/366871d1-e8c8-4ee5-b195-890c352b0896)

**Comment by harish08102004** [comment]
Hey @himeshparashar I can work on this.

**Comment by himeshparashar** [comment]
@harish08102004 ok you can start to work on this

**Comment by harish08102004** [comment]
![image](https://github.com/user-attachments/assets/c06b213e-2bb6-43b0-8e8a-9afcc96ff805)
I'm getting error with some clerk api key 
what should i do.

**Comment by Shobhit-Nagpal** [comment]
@harish08102004 hey, can you drop in an update on what's the progress?

**Comment by harish08102004** [comment]
hey @Shobhit-Nagpal I'm working on it can you give me some more time.
![image](https://github.com/user-attachments/assets/d2c720b3-e7b9-4b03-bfcf-d722f3880f90)

**Comment by harish08102004** [comment]
hey do I need to create a seperate page for dashboard or just i need to wrap it down in home page itself ?

**Comment by himeshparashar** [comment]
@harish08102004 separate page maybe /dashboard, and please try to match the website theme

**Comment by harish08102004** [comment]
Noted!

**Comment by himeshparashar** [comment]
![image](https://github.com/user-attachments/assets/0523c7cf-f704-4b74-97cc-dc7fc7d89a6f)

Like this clean and smooth UI design, but ensure consistency or draw inspiration from the internet (Dribbble, Pinterest).

**Comment by himeshparashar** [comment]
I would like to also wait for @harish08102004 , and try to combine both the things

**Comment by harish08102004** [comment]
Hey please assign someone else I tried my best but couldn't finish it.
Sorry.

**Comment by rudrapratap63** [comment]
@himeshparashar, could you please assign this issue to me? I will make sure the design integrates perfectly with the website's theme.
