### ISSUE TITLE
Add Automated Greeting Workflow

### ISSUE THREAD

**Issue by harish08102004** [himeshparashar/Social-Morph#24]
I propose to create a Github workflow named "Greetings". This workflow will automatically greet users who create new issues or pull requests in this repository. The Greetings will look like "Hi there! Thanks for opening this issue. We appreciate your contribution to this open - source project. We aim to respond or assign your issue as soon as possible .

Hey @himeshparashar I can work on this.

**Comment by himeshparashar** [comment]
I think it's not need and also this would be very low contribution , if you wish you can add adv workflow for build checking and other stuffs

**Comment by harish08102004** [comment]
Yeah I can do that also creating workflow for build checking.
