### ISSUE TITLE
the title and logo in the main page

### ISSUE THREAD

**Issue by jayanththalla** [himeshparashar/Social-Morph#25]
The navbar title and title of main page is not same 
please sign me @pa under both hacktoberfest and gssoc-ext

**Comment by iamsaura8h** [comment]
hey @jayanththalla ,
I am a UI/UX Designer so its occurs to me you need a branding logo on your web app . I will be more than happy to work on it so kindly Assign me this issue.
thank you.

**Comment by himeshparashar** [comment]
@jayanththalla title suggestion is very low kinda contribution

**Comment by himeshparashar** [comment]
@iamsaura8h you can go ahead with logo design
