### ISSUE TITLE
Improved Readme for better visiblity to new contributors

### ISSUE THREAD

**Issue by akhandpratap18** [himeshparashar/Social-Morph#28]
@himeshparashar your readme file is very monotonous and would not attract new contributors to contribute towards your project. I can help me make it better, I have recently made a level 2 contribution by enhancing the readme file

**Comment by akhandpratap18** [comment]
@himeshparashar assign it to me

**Comment by himeshparashar** [comment]
@akhandpratap18 any updates ?

**Comment by himeshparashar** [comment]
@akhandpratap18 ok
