### ISSUE TITLE
hey i saw a issue when you hover on dropdown it show list to far and when not hover it gone

### ISSUE THREAD

**Issue by viveksarkar0** [himeshparashar/Social-Morph#29]
hey i find this issue when user is not hovering it gone and it to far let me fix this for you assing me this issue under gssoc and hacktober fest 
<img width="1470" alt="Screenshot 2024-10-05 at 4 09 47 PM" src="https://github.com/user-attachments/assets/3600477f-fdc9-4796-8743-9551ef7d6b74">

**Comment by himeshparashar** [comment]
issue already in consideration https://github.com/himeshparashar/Social-Morph/issues/10

if you can create a PR first then it's your 👍

**Comment by viveksarkar0** [comment]
sir is my pull request add ?
@himeshparashar

**Comment by himeshparashar** [comment]
@viveksarkar0 yes its merged in the branch
