### ISSUE TITLE
fix the alignment of dropdown content of features link on the navbar

### ISSUE THREAD

**Issue by Aradhya-005** [himeshparashar/Social-Morph#30]
![image](https://github.com/user-attachments/assets/4d0fd913-4cb1-4068-b790-8b227746bedd)
while clicking on the dropdown of features link on navbar, the dropdown content is not align just below the features link as you shown in image. 
i would like to align it properly just below the features link. 
@himeshparashar please assign this task to me under GSSoC extended and Hacktoberfest

**Comment by himeshparashar** [comment]
Resolved
