### ISSUE TITLE
Feature request : Adding A Dark Theme 

### ISSUE THREAD

**Issue by Mandy1200** [himeshparashar/Social-Morph#34]
Adding A Dark/Light toggle button with feature

Sample

![Screenshot (60)](https://github.com/user-attachments/assets/b7fa9d8c-07b6-4579-b6ac-30c4c4f87dde)

![Screenshot (61)](https://github.com/user-attachments/assets/f05627f8-82b5-45c8-a463-c459f54dac41)

please assign this issue to me under GSSOC-etxd and Hackoctober fests

**Comment by himeshparashar** [comment]
not needed the light theme lgtm
