### ISSUE TITLE
Create Customizable and Secure Backend for User Authentication and Authorization

### ISSUE THREAD

**Issue by BhairabMahanta** [himeshparashar/Social-Morph#40]
**Description:**
**Issue:**
The current project uses **Clerk** for sign-in and sign-up, which works well for frontend authentication but presents some potential concerns:
- **Security Concerns**: Relying solely on third-party authentication services might expose the project to vulnerabilities, as sensitive data handling is not fully within our control.
- **Customizability**: The current solution limits the flexibility to customize login and registration pages according to specific project needs.
- **Backend Integration**: There is no dedicated backend for user management, which restricts the ability to implement features like role-based access control, advanced session handling, or custom validation logic.

**Proposed Solution:**
- Develop a custom **backend** for user registration, authentication, and authorization using **Node.js** and **JWT** for token-based authentication.
- Implement role-based access controls for different user types (e.g., user, admins).
- Create a fully customizable login and registration flow, with enhanced security layers (such as password hashing, MFA, and input validation).
- Ensure that the system can integrate smoothly with the existing frontend.

**Request for Review:**
I propose reviewing this issue to evaluate the risks and limitations of using **Clerk** alone, and discuss the benefits of moving to a more customizable and secure backend solution for authentication and authorization. This would grant the team more control over user data and security practices while also improving flexibility for future updates. 
---
Furthermore, Since the other projects required frontend teams to integrate the backend with frontend, ill leave the integration part to the frontend Team and basically, create a proper backend structure!

request: Please assign me this issue if you do not see any problems with it, along with gssocext, hacktoberfest and level labels thank you!

**Comment by BhairabMahanta** [comment]
Note: There wouldnt be any changes to clerk so until the backend and frontend integrates smoothly, it can work as it is and also be removed smoothly!

**Comment by himeshparashar** [comment]
@BhairabMahanta you can go ahead with custom auth or can also use next auth if you feel like , but for the db use postgres not mongodb or firebase

**Comment by BhairabMahanta** [comment]
> @BhairabMahanta you can go ahead with custom auth or can also use next auth if you feel like , but for the db use postgres not mongodb or firebase

okay, noted.

**Comment by himeshparashar** [comment]
@BhairabMahanta  this is the issue related to frontend for this you can refer this https://github.com/himeshparashar/Social-Morph/issues/12
