### ISSUE TITLE
continuation of issue #41

### ISSUE THREAD

**Issue by ShivanshPlays** [himeshparashar/Social-Morph#42]
After working on a pricing page under #41 issue, I can add add razorpay funcionality to accept pro payments and create protected admin dashboard for managing pro users.

I will protect your routes using razorpay sdk webhooks

I can work on this functionality  a level3
context: gssoc gssoc-ext hacktoberfest hacktoberfest-accepted

**Comment by himeshparashar** [comment]
@ShivanshPlays i think there are some updates in the Razorpay policy account , current not looking to add a payment gateway for now ,  i have to explore on this part which would be better
