### ISSUE TITLE
Issue Title: "Add Cursor-Following Animation"

### ISSUE THREAD

**Issue by AswaniBolisetti** [himeshparashar/Social-Morph#48]
@himeshparashar 
Issue Description: The website currently lacks interactive design elements that enhance user experience. I propose adding a cursor-following animation to create dynamic interactions where design elements move along with the mouse cursor, providing a more engaging and visually appealing experience.

I’d like to work on adding this feature. Please assign this issue to me under gssoc-ext, hacktoberfest-accepted, level

**Comment by himeshparashar** [comment]
@AswaniBolisetti  can you share a sample or an idea ? 

will the website element moves with the cursor or something else added elements will track the cursor ?

**Comment by AswaniBolisetti** [comment]
@himeshparashar like this and there are different styles also

https://github.com/user-attachments/assets/33787c36-04ed-4799-a505-169244dce1bc

**Comment by himeshparashar** [comment]
@AswaniBolisetti  Sorry but in reality this doesn't improve user experience in these type of website, companies avoid custom cursor on simple saas apps 

unless its a ui/ux or designer website then it's a plus point
