### ISSUE TITLE
Adding Blogs Page using MongoDB

### ISSUE THREAD

**Issue by swatified** [himeshparashar/Social-Morph#51]
Hey, since MongoDB is already connected. Why not make a blogs section which can intake and inflate values in cards? 

**HERES THE PROTOTYPE I AM THINKING OF :**
![image](https://github.com/user-attachments/assets/8d973daf-5c16-425b-a50d-b7e92fe59842)

Will use same font as overall one. Kindly assign me asap so that i can start working on it. labels: gssoc-ext hacktoberfest-accepted and level2 (id suggest you give me that based on final work later on. it could be more or less as you think its worth of).

**Comment by swatified** [comment]
@himeshparashar @Shobhit-Nagpal

**Comment by himeshparashar** [comment]
duplicate to https://github.com/himeshparashar/Social-Morph/issues/37
