### ISSUE TITLE
Adding Signup Window at "Get Started" using Clerk

### ISSUE THREAD

**Issue by swatified** [himeshparashar/Social-Morph#52]
I want to add a login popup/webpage which gets redirected when user clicks get started.

**PROTOTYPE**
![image](https://github.com/user-attachments/assets/8e4fb259-5172-4852-b7c1-03347eafeee6)

Kindly assign me under gssoc-ext and hacktoberfest-accepted so that I can start working on the same asap

**Comment by swatified** [comment]
@himeshparashar @Shobhit-Nagpal

**Comment by himeshparashar** [comment]
## Duplicate
https://github.com/himeshparashar/Social-Morph/issues/40

https://github.com/himeshparashar/Social-Morph/issues/12

issue already in consideration
