### ISSUE TITLE
adding code-of_conduct.md

### ISSUE THREAD

**Issue by jyothimanoj12** [himeshparashar/Social-Morph#58]
A Code of Conduct ensures inclusivity, prevents harassment, clarifies behavioral expectations, encourages professionalism, and fosters a safe, welcoming community for contributors.

plz assisn me this issue under gsoc-extended , level 1 , hacktoberfest-accepted tag

**Comment by MitulSonagara** [comment]
@himeshparashar 

I have already made PR for this issue and as you told me to create new issue for that PR and mention you. But this issue is already here so i am mentioning you here.

Please review PR and merge it.

PR #59

**Comment by himeshparashar** [comment]
@MitulSonagara PR has been merged 👍
