### ISSUE TITLE
I want to make your website more attractive.

### ISSUE THREAD

**Issue by Bhum-ika** [himeshparashar/Social-Morph#6]
Hi, I saw your website. The design is beautiful, and the color combination is great.

If you add scroll animations and motion components, it will increase the time clients spend on your website and make it more eye-catching. Animations like popping up videos and text scrolling from the left as the website is scrolled down will really help.
 For that, I can use Framer Motion.

**Comment by himeshparashar** [comment]
Can you please elaborate more with what changes you want to do ?
and no need of over animating as this can impact website performance .

Or you can also start working on the improvement and just create a PR after that
