### ISSUE TITLE
mobile view layout

### ISSUE THREAD

**Issue by jainaryan04** [himeshparashar/Social-Morph#61]
please add gssoc-ext and hacktoberfest-accepted labels
@himeshparashar @sanjay-kv @Shobhit-Nagpal @LakshitAgarwal 

1. remove this gap
![image](https://github.com/user-attachments/assets/b89d645c-00fd-4d3f-ad39-6dfc6342b7bb)

2. shift the icons to the corners
![image](https://github.com/user-attachments/assets/adb733c3-d75b-48b2-a8fd-c1a9302d923a)

**Comment by Shobhit-Nagpal** [comment]
hey @jainaryan04, these are issues on the recent build of the site?

**Comment by jainaryan04** [comment]
@Shobhit-Nagpal yes

**Comment by Shobhit-Nagpal** [comment]
@himeshparashar is this issue relevant rn?

**Comment by himeshparashar** [comment]
@jainaryan04 you can work on this issue
