### ISSUE TITLE
Add signin/signup

### ISSUE THREAD

**Issue by haseebzaki-07** [himeshparashar/Social-Morph#65]
I want to add login/siginin backend to the website @himeshparashar

**Comment by Shobhit-Nagpal** [comment]
hey @haseebzaki-07, we're using clerkjs for authentication. won't be needing separate auth routes. closing this issue :))

**Comment by himeshparashar** [comment]
@Shobhit-Nagpal note still looking for a custom login and signup page UI

**Comment by himeshparashar** [comment]
@haseebzaki-07 looks already someone has raised the issue https://github.com/himeshparashar/Social-Morph/issues/12

**Comment by himeshparashar** [comment]
@Shobhit-Nagpal @myselfshivams i think he is not working on many issues and also closing them without working on them we need to look into this,  so that other contributors may work on the issue

**Comment by haseebzaki-07** [comment]
@himeshparashar @Shobhit-Nagpal its been quite a time i rasied this issue. Would it be possible that you assign me this issue as I will provide this is in one day itself
