### ISSUE TITLE
Issues related to responsiveness 

### ISSUE THREAD

**Issue by adityapandey23** [himeshparashar/Social-Morph#7]
I love the current UI of the website, but I want to enhance by adding some responsiveness in places like this:

![image](https://github.com/user-attachments/assets/64c49e5e-3294-4585-b302-d8f1e67382b1)

![image](https://github.com/user-attachments/assets/b949040e-cf26-47ac-b28c-049fcaeb9aab)

![image](https://github.com/user-attachments/assets/36217ea3-e47c-4e8f-89c8-5af139eec85b)

It would be really great if you would assign this issue to me so that I can start working on it!

**Comment by himeshparashar** [comment]
@adityapandey23  issue assigned to you,
you can go ahead with make the website responsive

**Comment by adityapandey23** [comment]
Hey @himeshparashar , I have created a pr related to this issue #18 .
Also, will this contribution be counted towards Ggsoc-ext hacktoberfest contribution?
