### ISSUE TITLE
Want to add Rating Us functionality

### ISSUE THREAD

**Issue by Suvadip-sana** [himeshparashar/Social-Morph#70]
https://github.com/user-attachments/assets/e862337d-9eda-4339-b77e-f94f0bead90c

I want to add a **Rating Us** functionality for this website.
I developed the same thing as you seen on video.

For now it only display a greetings as alert message.
Further you can add a backend functionality to display the ratings in webpage. Though it's an open source project, If i built this functionality, it would be great for you and other also for further improvement in this field.

Please assign me this ISSUE. I want to implement this feature.

**Comment by Suvadip-sana** [comment]
@Shobhit-Nagpal 
What you think?

**Comment by himeshparashar** [comment]
@Suvadip-sana also add a contact us form 
![image](https://github.com/user-attachments/assets/c1b4390d-2d15-4159-a4ee-e91a54c41ce3)

something like that but which matches our UI and along with this you may implement a rate us functionality also

**Comment by Suvadip-sana** [comment]
@himeshparashar 
means there is now stars based rating? Only this type of 'Get in touch' form? Along with this contact details?
Should i create seperate page for this? or what?

@himeshparashar Please clarify this?

**Comment by himeshparashar** [comment]
@Suvadip-sana  don't make any new page just make it above the footer on home page.
and along with get in touch also add a rate us button

**Comment by Suvadip-sana** [comment]
@himeshparashar 

https://github.com/user-attachments/assets/df643de4-0c63-4e43-8062-19a00a9141e7

It's ready.
Give me atleast label-2. 
Because Initially i raised the issue only for 'rate us'  features.   But I implement two form as you say.  
Please considered this.

I made a PR.

Thank You.

**Comment by Suvadip-sana** [comment]
@himeshparashar 
Is this fine?

**Comment by Suvadip-sana** [comment]
@himeshparashar 

Ok i made a PR.

And please give me atleast `label-2`

Thank you!
