### ISSUE TITLE
Want to make whole footer better, more visually appealing.

### ISSUE THREAD

**Issue by Suvadip-sana** [himeshparashar/Social-Morph#71]
For now the whole footer is too simple compare to the website other part. Means the other part of the website is more stylish than the footer. Need a improvement of the footer.

I am able to make this footer like this according to your websites color combination, if you assign me this task -->

https://github.com/user-attachments/assets/4c949ce2-9945-4a43-8596-5b5f1c8b9c34

Please assign me this task. I want to improve this part

**Comment by Shobhit-Nagpal** [comment]
hey @Suvadip-sana, the footer demonstration looks amazing firstly.

secondly, what ideas do you have for social morph's footer?

**Comment by Suvadip-sana** [comment]
@Shobhit-Nagpal 
1> Ok see I think the get started part placed on the right side as it is. Although it's not working for now.

2> And in the left part I think the platform name along with sort description is perfect because it's an standard structure for modern websites. and under this i placed the social media links. For now it's only linkdIn and twiter. Here I add Discord and Github also with addition.

3> In the middle for now it's only *Quick links* which is completely fine  but my suggestion is here should be a **Legal** part which contain all legal things like privacy policy, T & C, cooky Policy, because it's and third part platform and user should be aware for legal thinks.


Let me see, what you think about this. What you want?

**Comment by Suvadip-sana** [comment]
@Shobhit-Nagpal 
Please tell me your opinion?

**Comment by Suvadip-sana** [comment]
@himeshparashar 

Here please assign me this ISSUE.

**Comment by himeshparashar** [comment]
currently not looking forward to work on footer for now
