### ISSUE TITLE
[FEAT] : Multi-lingual Support to Social Morph.

### ISSUE THREAD

**Issue by IkkiOcean** [himeshparashar/Social-Morph#78]
#### **Description:**
To enhance the accessibility and reach of the Social Morph platform, we need to introduce multi-lingual support using the Google Translate API. This feature will allow users from various linguistic backgrounds to interact with the platform in their preferred language, making it easier for them to understand and engage with the content.

#### **Feature Request:**
- Implement multi-lingual support across the Social Morph platform.
- Use Google Translate API for real-time translation of the platform’s UI text, user posts, and comments.
- Allow users to select their preferred language, and automatically translate content as per their selection.
- Support for at least the following languages initially: English, Spanish, French, Hindi, and Mandarin.

#### **Expected Behavior:**
- Users should be able to toggle between supported languages via a language switcher in the footer.
- All user-generated content (posts, comments) should be translated automatically into the selected language using the Google Translate API.
- Platform UI (buttons, headers, menus) should adjust to the selected language for better user experience.

#### **Use Cases:**
- **Global Reach**: Non-English speaking users can interact with Social Morph without language barriers.
- **Increased Engagement**: Users are more likely to engage when content is available in their native language.
- **User Convenience**: Automatic translation of posts and comments improves accessibility.

**Please assign level 3 for this**

**Comment by himeshparashar** [comment]
actually not looking to target non-english speakers for now, coz this may need the content generation and post generation to be multilingual also

**Comment by IkkiOcean** [comment]
> actually not looking to target non-english speakers for now, coz this may need the content generation and post generation to be multilingual also

actually no, the post and content of the page will be automatically trsnslated using google translate API. let me show you the demo


https://github.com/user-attachments/assets/8305c67e-916b-4550-bc60-f22de2b61354
