### ISSUE TITLE
Quick links and Nav links aren't functioning properly 

### ISSUE THREAD

**Issue by DarshanchGIT** [himeshparashar/Social-Morph#8]
The FAQ quick links aren’t directing to the FAQ section, and the navigation links are unresponsive—they don’t redirect anywhere. Please assign this issue to me, and I’ll fix both the quick links and nav links to ensure proper functionality.

**Comment by DarshanchGIT** [comment]
Pa this issue to me

**Comment by himeshparashar** [comment]
@DarshanchGIT  I have though of implementing a backend flow with AI integrated that can generate social media post , if you have any idea or approach then please share else no need to improve this for now
