### ISSUE TITLE
Dropdown Menu Disappears When Hovering Over Options

### ISSUE THREAD

**Issue by amitb0ra** [himeshparashar/Social-Morph#92]
#### **Issue Description**:
The dropdown menu under the "Features" button disappears as soon as the user tries to hover over the options (Generate, Schedule, Design). This makes it difficult for users to interact with the dropdown, and they are unable to select any option.

#### **Steps to Reproduce**:
1. Hover over the "Features" button.
2. Try to move the cursor down to the options in the dropdown.
3. The dropdown menu closes before the options can be clicked.

https://github.com/user-attachments/assets/7d97cf76-eb8b-4824-8799-720e074fcf67

#### **Proposed Solution**:
Adjust the dropdown behavior so that it stays open when the user moves the mouse between the button and the dropdown list, eliminating any gaps that trigger the menu to close prematurely.

https://github.com/user-attachments/assets/09052f12-2872-4cb4-93df-4b59ccd7cae7

Additionally, please assign this issue under **gssoc-ext** and **hacktoberfest**.

**Comment by himeshparashar** [comment]
@amitb0ra you can start working on this

**Comment by amitb0ra** [comment]
> @amitb0ra you can start working on this

i have already linked a fix PR.
