### ISSUE TITLE
Add Animations to FAQ Section

### ISSUE THREAD

**Issue by sezallagwal** [himeshparashar/Social-Morph#95]
Description:
Enhance the user experience by adding smooth animations to the FAQ section. The animations should improve the interactivity and visual appeal when a user expands or collapses a question.

Requirements:

Expand/Collapse Animation:
Apply a smooth sliding animation when expanding and collapsing the FAQ items.
The transition should be fast enough to keep the interaction responsive but slow enough for a smooth effect (e.g., 0.3s - 0.5s duration).

Icon Animation:
Rotate or change the icon next to each question when expanded and revert back when collapsed.
The icon animation should synchronize with the expand/collapse animation.

Fade-in Effect:
Add a subtle fade-in effect for the content when a question is expanded.
Responsive Behavior:

Ensure that the animations work well across all device sizes (desktop, tablet, mobile).

Acceptance Criteria:
 The FAQ section should animate smoothly when a question is expanded or collapsed.
 Icons should transition visually to indicate the expanded/collapsed state.
 Animations should be consistent across all supported browsers and devices.
 No performance issues should arise due to the added animations.

@himeshparashar please assign it to me under gssoc-ext and hacktoberfest

**Comment by himeshparashar** [comment]
@sezallagwal you can work on this issue
