### ISSUE TITLE
Footer Improvement

### ISSUE THREAD

**Issue by Bhum-ika** [himeshparashar/Social-Morph#96]
Currently the footer is not having the optimal Text size and font size , also the logos are too big and the Twitter logo is old and the line 'LinkedIn content patient Made Easy' should not be in centre so basically it can be made better with some modifications. 
I would like to work on this issue. 
Kindly assign this issue to me under hactoberfest, gssoc-ext and relevant tags.
![Screenshot 2024-10-15 095107](https://github.com/user-attachments/assets/4730a45e-ca2d-4419-b284-918acee5cb4f)

**Comment by himeshparashar** [comment]
@Bhum-ika also there looks some alignment issue and also just add the new logo to the footer
