### ISSUE TITLE
In footer, Text in "Business Website" Field Not Visible in 'Get Posts' Section

### ISSUE THREAD

**Issue by Ankul8471** [himeshparashar/Social-Morph#99]
https://github.com/user-attachments/assets/0d482b19-c8a3-491e-ad09-6ea1bda3d317

When attempting to type into the "Business Website" input field in the 'Get Posts' section, the text is not visible. This issue makes it difficult for users to see what they are typing, potentially leading to incorrect or incomplete information being entered. This seems to be a problem with the CSS, where the text color might be the same as the background or transparency may have been set incorrectly.

Steps to Reproduce:

Navigate to the 'Get Posts' section on the homepage.
Try typing a business website in the input field.
Observe that the text is not visible as you type.
Expected Outcome: Text should be clearly visible when typed into the input field.

Actual Outcome: Text is not visible, making it hard to see what's being entered.

Suggested Fix: Check the input field’s text color and background color settings in the CSS. Ensure they are different and that the text color contrasts with the background for better visibility.
![newp](https://github.com/user-attachments/assets/884f2647-9270-4fae-b8f6-623ca286e74f)

**Comment by Ankul8471** [comment]
@himeshparashar   Hello please assign me this issue

**Comment by himeshparashar** [comment]
@Ankul8471 this shouldn't take more than a day waiting you to finish this ASAP

**Comment by himeshparashar** [comment]
@Ankul8471 sorry but this issue already have been resolved now in this pr https://github.com/himeshparashar/Social-Morph/pull/84

**Comment by Ankul8471** [comment]
Ok no problem
